import {ISkills} from "@/type/skills_type";

export const skills:ISkills[] = [

    {
        title:"Frontend",
        tech:[
            {
                label:"Typescript",
                image:"icons8-typescript.png"
            },
            {
                label:"Javascript",
                image:"icons8-javascript.png"
            },
            {
                label:"NextJs",
                image:"icons8-nextjs.png"
            },
            {
                label:"ReactJs",
                image:"icons8-react.png"
            },
            {
                label:"Tailwind ",
                image:"icons8-tailwind.png"
            },
        ]
    },
    {
        title:"Mobile",
        tech:[
            {
                label:"Dart",
                image:"icons8-dart.png"
            },
            {
                label:"Flutter",
                image:"icons8-flutter.png"
            },
        ]
    },
    {
        title:"Backend",
        tech:[
            {
                label:"Java",
                image:"icons8-java.png"
            },
            {
                label:"Spring boot",
                image:"icons8-spring-boot.png"
            },
            {
                label: "Keycloak",
                image:"keycloak.jpg"
            }
        ]
    },
    {
      title:"Problem solving",
      tech:[
          {
              label:"Python",
              image:"icons8-python.png"
          }
      ]
    }
    ,
    {
        title:"DataBases",
        tech:[
            {
                label:"Postgresql",
                image:"icons8-postgres.png"
            },
            {
                label:"Mysql",
                image:"icons8-mysql.png"
            },
            {
                label:"Firebase",
                image:"icons8-firebase.png"
            },
            {
                label:"MongoDb",
                image:"icons8-mongodb.png"
            },
            {
                label:"Redis",
                image:"icons8-redis.png"
            },
            {
                label:"Oracle",
                image:"icons8-oracle.png"
            },
            {
                label:"Elastic search",
                image:"icons8-elasticsearch.png"
            },
        ]
    },{
        title:"Tools",
        tech:[
            {
                label:"Git",
                image:"icons8-git.png"
            },
            {
                label:"Github",
                image:"icons8-github.png"
            },
            {
                label:"Docker",
                image:"icons8-docker.png"
            },
            {
                label:"Nginx",
                image:"icons8-nginx.png"
            },
            {
                label:"Trello",
                image:"icons8-trello.png"
            },
        ]
    }
]